# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='human',
            name='operator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='categorie',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='object',
            name='graspable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='orientation',
            field=models.IntegerField(default=3.1416),
        ),
        migrations.AddField(
            model_name='entity',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Position'),
        ),
    ]
