# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170608_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('id',)},
        ),
    ]
