# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170612_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='position',
        ),
        migrations.AddField(
            model_name='entity',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='z',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
