# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170612_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('x3', models.FloatField()),
                ('x4', models.FloatField()),
                ('y1', models.FloatField()),
                ('y2', models.FloatField()),
                ('y3', models.FloatField()),
                ('y4', models.FloatField()),
                ('room_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='x',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='y',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='z',
        ),
        migrations.RemoveField(
            model_name='human',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='object',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='object',
            name='graspable',
        ),
        migrations.RemoveField(
            model_name='object',
            name='orientation',
        ),
        migrations.AddField(
            model_name='entity',
            name='x_position',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='y_position',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='z_position',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='person_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Entity'),
        ),
        migrations.AddField(
            model_name='room',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Entity'),
        ),
    ]
