# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170715_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='entity',
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='x_position',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='y_position',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='z_position',
        ),
        migrations.RemoveField(
            model_name='human',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='human',
            name='person_name',
        ),
        migrations.RemoveField(
            model_name='object',
            name='color',
        ),
        migrations.RemoveField(
            model_name='object',
            name='type',
        ),
        migrations.AddField(
            model_name='entity',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='z',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='operator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='categorie',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='object',
            name='graspable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='orientation',
            field=models.IntegerField(default=3.1416),
        ),
        migrations.DeleteModel(
            name='Waypoint',
        ),
    ]
