# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170715_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='x_position',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='y_position',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='z_position',
        ),
        migrations.AddField(
            model_name='entity',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='z',
            field=models.IntegerField(null=True),
        ),
    ]
