# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170715_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='doors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Door'),
        ),
    ]
