# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170716_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
                ('z', models.IntegerField(null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Room')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='surface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Surface'),
        ),
    ]
