# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170716_0228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Surface',
            new_name='AccessPoint',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='surface',
            new_name='access_point',
        ),
    ]
