# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170716_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='entity',
        ),
        migrations.DeleteModel(
            name='Waypoint',
        ),
    ]
