# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170716_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Entity'),
        ),
    ]
