# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170717_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='probabilty',
            new_name='probability',
        ),
    ]
